title:            Redhill Aviation
description:      Describe your website.
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://redhillaviation.co.uk

# Owner/author information
owner:
  name:           Redhill Aviation
  avatar:         bio-photo.jpg
  bio:            "Describe your self."
  email:          your@email.com

# Analytics and webmaster tools stuff goes here
google_analytics:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Us
    url: /about-us
  - title: Experience Flights
    url: /experience-flights/
  - title: Training
    url: /training/
    sublinks:
      - title: Overview
        url: /training/
      - title: Learning to fly
        url: /learning-to-fly/
      - title: Night Rating
        url: /night-rating/
      - title: IMC
        url: /imc/
  - title: Aircraft Hire
    url: /aircraft-hire/
  - title: Maintenance
    url: /aircraft-maintenance/
  - title: Aircraft Lease
    url: /aircraft-lease/
  - title: Our Fleet
    url: /our-fleet/
  - title: Contact Us
    url: /contact-us/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    GB
future:      true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
